### ISSUE TITLE
[DRAFT] AMP Smartlinks Intent to Implement

### ISSUE THREAD

**Issue by PhilWinchester** [hellonarrativ/amphtml#2]
Hi AMP community,

I work for a commerce content monetization platform called Narrativ. We have a few out of the box javascript integrations we offer our clients to help monetize their publications. To help our publishers monetize fully through AMP we would like to add an extension that utilizes our smartlink technology.

A few weeks ago the `amp-skimlinks` extension was merged that offers a similar service to us. They created a service called `link-rewriter` which handles event listeners, link swapping, and click tracking on anchor tags. We aim to utilize that service in our extension since that is a shared feature in both of our platforms. 

Our company believes in the core AMP principles and would like to work alongside your team develop an extension that offers a full suite of publisher tools and an optimized reader experience. 

## amp-smartlinks
For our initial implementation, `amp-smartlinks` will require API calls to fetch the publishers config in our system, a page load event (using `extension-analytics`), and finally a POST call with all anchor tags on the page to be filtered and monetized according to our publisher partnership in our system. All monetized links will be returned and placed in the DOM using `link-rewriter`.

Our documentation on our vanilla JS tag can be found [here](http://docs.narrativ.com/en/stable/tagpublisher.html) and our documentation around Linkmate can be found [here](http://docs.narrativ.com/en/stable/linkmate.html).
```HTML
<amp-smartlinks
    layout="nodisplay"
    nrtv-account-name="examplepublisher"
    linkmate='true'
    exclusive-links='false'
></amp-smartlinks>
```

**Comment by csdev** [comment]
Is `nrtv-slug` too confusing? Should we do something like `account-name` or `nrtv-account-name` for consistency with the terminology in the [API docs](http://docs.narrativ.com/en/stable/tagpublisher.html#implementation)?

**Comment by pbecotte** [comment]
I think my only question is if we even want to include the auction step at this point- I don't think we need that until we talk about DOM mutation, and would wonder if mentioning something that we don't actually need is a good idea

**Comment by PhilWinchester** [comment]
You mean just swap each href with a `shop-link` and run a click auction for each one? If you're ok with that then it will make my life easier :)

**Comment by pbecotte** [comment]
no reason to do impression auctions here I don't think- lets have linkmate + click-auction be the first pass

**Comment by PhilWinchester** [comment]
😍 Works for me. Will update and re-post!

**Comment by pbecotte** [comment]
I like it a lot, no suggestions
